name: Pull Request Setup
on:
  pull_request:
    types: [opened, ready_for_review, edited]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.0
        with:
          configuration-path: ".github/pr_auto_assign_config.yml"
  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          REQUIRED_LABELS_ANY: "enhancement,architecture,bug,documentation"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label [enhancement, architecture, bug, documentation]"
          BANNED_LABELS: "duplicate,invalid,question,wontfix"
          BANNED_LABELS_DESCRIPTION: "The [duplicate, invalid, question, wontfix] labels are banned"
